language: rust
rust:
- nightly
cache: cargo
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - binutils-arm-none-eabi
env:
  matrix:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=thumbv6m-none-eabi
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt-nightly
- which xargo || cargo install xargo
- rustup component list | grep 'rust-src.*installed' || rustup component add rust-src
- set -e
script:
- ". ./ci/build.sh"
- cargo fmt -- --write-mode=diff
# - ". ./ci/build_examples.sh"
# - ". ./ci/test.sh"
after_script:
- set +e
