[package]
authors = ["Pollen Robotics <contact@pollen-robotics.com>"]
name = "robus"
publish = false
version = "0.1.0"

[dependencies.clippy]
optional = true
version = "*"

[target.'cfg(not(target_arch = "arm"))'.dependencies.mockup_hal]
git = "https://github.com/pollen/stm32-mockup-hal"
[target."cfg(not(target_arch = \"arm\"))".dev-dependencies]
rand = "0.3.18"

[target."cfg(target_arch = \"arm\")".dependencies]
cortex-m = "0.3.1"
cortex-m-rt = "0.3.6"
cortex-m-semihosting = "0.2.0"
[target."cfg(target_arch = \"arm\")".dependencies.alloc-cortex-m0]
git = "https://github.com/pollen/alloc-cortex-m0"
[target."cfg(target_arch = \"arm\")".dependencies.stm32f0_hal]
git = "https://github.com/pollen/stm32f0"
