[package]
authors = ["Pollen Robotics <contact@pollen-robotics.com>"]
name = "robus"
publish = false
version = "0.2.0"
license = "LGPL-3.0"

[dependencies.clippy]
optional = true
version = "*"

[profile.dev]
opt-level = 0
debug = true
codegen-units = 1
[profile.release]
opt-level = 3
debug = false
codegen-units = 1

[target.'cfg(not(target_arch = "arm"))'.dependencies.mockup_hal]
git = "https://github.com/pollen-robotics/stm32-mockup-hal"
[target."cfg(not(target_arch = \"arm\"))".dev-dependencies]
rand = "0.3.18"

[target."cfg(target_arch = \"arm\")".dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.3"
nb = "0.1.1"

[target."cfg(target_arch = \"arm\")".dependencies.stm32f0_hal]
git = "https://github.com/pollen-robotics/stm32f0"
features = ["use_alloc"]

[target."cfg(target_arch = \"arm\")".dev-dependencies]
cortex-m-rt = "=0.3.7"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.1.0"
