[package]
authors = ["Pollen Robotics <contact@pollen-robotics.com>"]
name = "robus"
publish = false
version = "0.1.0"
license = "LGPL-3.0"

[dependencies.clippy]
optional = true
version = "*"

[profile.dev]
opt-level = 0
debug = true
codegen-units = 1
[profile.release]
opt-level = 3
debug = false
codegen-units = 1

[target.'cfg(not(target_arch = "arm"))'.dependencies.mockup_hal]
git = "https://github.com/pollen/stm32-mockup-hal"
[target."cfg(not(target_arch = \"arm\"))".dev-dependencies]
rand = "0.3.18"

[target."cfg(target_arch = \"arm\")".dependencies]
cortex-m = "0.3.1"
[target."cfg(target_arch = \"arm\")".dev-dependencies]
cortex-m-rt = "=0.3.7"
[target."cfg(target_arch = \"arm\")".dependencies.alloc-cortex-m0]
path = "../alloc-cortex-m0/"
[target."cfg(target_arch = \"arm\")".dependencies.stm32f0_hal]
git = "https://github.com/pollen/stm32f0"
[target."cfg(target_arch = \"arm\")".dependencies.stm32f0x2]
git = "https://github.com/pollen/stm32f0"
