[package]
authors = ["Pollen Robotics <contact@pollen-robotics.com>"]
name = "robus"
publish = false
version = "0.1.0"

[dev-dependencies]
rand = "0.3.18"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.mockup_hal]
git = "https://github.com/pollen/stm32-mockup-hal"
